# IDE
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4G
org.gradle.warning.mode=all
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.21.11
yarnMappings=1.21.11+build.4
loaderVersion=0.18.4
# Fabric API
fabricVersion=0.141.3+1.21.11
loomVersion=1.15-SNAPSHOT
# Mod Properties
modVersion=2026.2.1
mavenGroup=dev.syoritohatsuki
archivesBaseName=ducky-updater-rework
# Kotlin
systemProp.kotlinVersion=2.1.21
fabricKotlinVersion=1.13.3+kotlin.2.1.21
# Dependencies
ktorVersion=3.1.3
