[versions]
fabric-api = "0.161.0+26.3"
fabric-loader = "0.19.5"
fabric-loom = "1.18-SNAPSHOT"
fabric-language-kotlin = "1.14.1+kotlin.2.4.20"
faststats = "0.29.0+mc26.1-26.3"
kotlin = "2.4.20"
ktor = "3.6.0"
hikari = "7.1.0"
minecraft = "26.3"
modmenu-badges = "2026.3.1"
modrinth-minotaur = "2.+"
sqlite = "3.53.4.0"
zip4j = "2.11.6"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
faststats = { module = "dev.faststats.metrics:fabric", version.ref = "faststats" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu-badges = { module = "maven.modrinth:modmenu-badges-lib", version.ref = "modmenu-badges" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "modrinth-minotaur" }
