[versions]
fabric-api = "0.153.0+26.2"
fabric-loader = "0.19.3"
fabric-loom = "1.17-SNAPSHOT"
fabric-language-kotlin = "1.13.12+kotlin.2.4.0"
faststats = "0.27.3-pre2+mc26.1-26.3"
kotlin = "2.4.0"
ktor = "3.5.0"
hikari = "7.1.0"
minecraft = "26.2"
modmenu-badges = "2026.3.1"
modrinth-minotaur = "2.+"
sqlite = "3.53.2.0"
zip4j = "2.11.6"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
faststats = { module = "dev.faststats.metrics:fabric", version.ref = "faststats" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-events = { module = "io.ktor:ktor-events-jvm", version.ref = "ktor" }
ktor-http-cio = { module = "io.ktor:ktor-http-cio-jvm", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http-jvm", version.ref = "ktor" }
ktor-io = { module = "io.ktor:ktor-io-jvm", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network-jvm", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls-jvm", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx-jvm", version.ref = "ktor" }
ktor-utils = { module = "io.ktor:ktor-utils-jvm", version.ref = "ktor" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu-badges = { module = "maven.modrinth:modmenu-badges-lib", version.ref = "modmenu-badges" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

[bundles]
ktor = [
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-events",
    "ktor-http-cio",
    "ktor-http",
    "ktor-io",
    "ktor-network",
    "ktor-network-tls",
    "ktor-serialization",
    "ktor-serialization-kotlinx-json",
    "ktor-serialization-kotlinx",
    "ktor-utils",
]

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "modrinth-minotaur" }
